import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Calculadora Senac 2025 com NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`bg-[#454545] `}>{children}</body>
    </html>
  );
}
